name: Generate Snake

on:
  schedule:
    # Jalan otomatis setiap 24 jam (tengah malam)
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Generate animasi ular dari kontribusi GitHub
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: rey2305
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Push file svg ke branch 'output' (versi terbaru yang resmi)
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}